languageCode = "zh-cn"
title = "Wei's blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Wei"
  description = "Freedom should be an opportunity that can make he becomes better."
  github = "yuweizzz"
  email = "yuweiy@foxmail.com"
  url = "https://yuweizzz.github.io/"
  keywords = "blog, google analytics"
  rss = false
  lastmod = true
  favicon = "/images/favicon.svg"
  headerIcon = "/images/github-mark-white.png"
  location = "China"
  custom_js = "/js/CustomLive2D.js"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "G-RFSQDKSFR1"
