name: lint docs
on: 
  push:
    branches:
      - main

jobs:
  build:
    name: lint docs
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: lint docs
        uses: github/super-linter@v4
        env:
          FILTER_REGEX_INCLUDE: ^content/
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
